In [34]:
import pandas as pd
import numpy as np
import os

In [35]:
os.chdir('/Users/yi.hs/cs119/cs-119-bigdata/week3')

In [36]:
os.getcwd()

'/Users/yi.hs/cs119/cs-119-bigdata/week3'

In [5]:
taxi_data = pd.read_csv('chicago-taxi-rides.csv')
taxi_data.head()

pickup_community_area  dropoff_community_area  trips
0                   14.0                      19   2107
1                   14.0                      24   5370
2                   29.0                      29   2759
3                   29.0                      25    313
4                   41.0                      44   1693

In [58]:
def prepare_matrix():
    """
    Args : None
    Objective : imports and intialize matrix
    Returns : Matrix
    """

    taxi_data = pd.read_csv('chicago-taxi-rides.csv')
    taxi_data_cleaned = taxi_data.dropna()

    taxi_mat = np.zeros(shape=(77,77))
    for idx in range(taxi_data_cleaned.shape[0]):
        row, col, val = taxi_data_cleaned.iloc[idx,:]
        row, col = int(row -1), int(col -1)
        taxi_mat[row, col] = val
        
    taxi_matrix = pd.DataFrame(taxi_mat)
    
    return (taxi_matrix / taxi_matrix.sum()).to_numpy()

In [59]:
taxi_matrix= prepare_matrix()

In [60]:
taxi_matrix

array([[2.04951556e-01, 8.39604215e-02, 1.32752676e-02, ...,
        7.76638708e-04, 3.76905678e-03, 3.96100068e-02],
       [5.20446647e-02, 3.51053363e-01, 6.82917486e-03, ...,
        9.31966449e-04, 3.05156742e-03, 2.49612208e-02],
       [7.69746331e-02, 4.57013134e-02, 1.99002197e-01, ...,
        2.48524386e-03, 1.13594301e-02, 1.00183120e-01],
       ...,
       [3.70292883e-06, 6.21392042e-06, 6.84075151e-06, ...,
        9.86331159e-02, 1.53025899e-05, 5.06090376e-06],
       [6.63712964e-02, 6.40572343e-02, 3.99105230e-02, ...,
        7.11401056e-02, 1.70518203e-01, 6.00948582e-02],
       [1.28523105e-01, 9.25252751e-02, 6.43888367e-02, ...,
        1.55327742e-03, 1.03797756e-02, 2.34399975e-01]], shape=(77, 77))

In [9]:
rnk_vec

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [51]:
def TrafficRank(iter):
    # value Error
    # if not(0<= iter <=10):
    #     raise ValueError ("Iter value must be between 0 and 10")
    
    b = 0.85
    M = prepare_matrix()
    n = 77
    r = np.ones(n) / n
    
    if iter == 0:
        return r
    
    for _ in range(iter):
        r_next = b * (M @ r) + (1-b)/ n * np.ones(n)
        r = r_next
    
    return r.to_numpy()

In [52]:
print(type(TrafficRank(1)))

<class 'numpy.ndarray'>


In [53]:
TrafficRank(1)

array([0.00776147, 0.00960348, 0.01694584, 0.00909372, 0.00814903,
       0.04232735, 0.02560252, 0.13168099, 0.00247255, 0.00553273,
       0.01130359, 0.00387072, 0.00540578, 0.00850391, 0.00638912,
       0.01117593, 0.00440525, 0.00345422, 0.0046571 , 0.00318023,
       0.00844878, 0.01658647, 0.00415843, 0.0307963 , 0.0059357 ,
       0.003596  , 0.00421173, 0.07281711, 0.00360521, 0.00455325,
       0.00571386, 0.12389652, 0.02284753, 0.00599213, 0.00886282,
       0.00444685, 0.00481108, 0.00749272, 0.01078384, 0.00511632,
       0.02389159, 0.00804396, 0.00967289, 0.01183789, 0.00515568,
       0.00536155, 0.00390107, 0.00630305, 0.01030815, 0.00503089,
       0.00649308, 0.00324612, 0.00518765, 0.00438389, 0.00401442,
       0.05096913, 0.00429187, 0.00565567, 0.01070814, 0.00453756,
       0.00512222, 0.00393777, 0.00411494, 0.00492646, 0.00396393,
       0.00487296, 0.00524734, 0.00558959, 0.00785244, 0.00514448,
       0.00498904, 0.0030396 , 0.00450651, 0.00264924, 0.00366

In [45]:
for i in range(12): 
    print("i is : ", i , "and TrafficRank is : ", TrafficRank(i))

i is :  0 and TrafficRank is :  0     0.012987
1     0.012987
2     0.012987
3     0.012987
4     0.012987
        ...   
72    0.012987
73    0.012987
74    0.012987
75    0.012987
76    0.012987
Length: 77, dtype: float64
i is :  1 and TrafficRank is :  0     0.007761
1     0.009603
2     0.016946
3     0.009094
4     0.008149
        ...   
72    0.004507
73    0.002649
74    0.003665
75    0.051251
76    0.013945
Length: 77, dtype: float64
i is :  2 and TrafficRank is :  0     0.006221
1     0.007271
2     0.016433
3     0.007397
4     0.007654
        ...   
72    0.002987
73    0.002104
74    0.002511
75    0.047121
76    0.012620
Length: 77, dtype: float64
i is :  3 and TrafficRank is :  0     0.005543
1     0.006112
2     0.015677
3     0.006528
4     0.007232
        ...   
72    0.002647
73    0.002069
74    0.002331
75    0.046887
76    0.011615
Length: 77, dtype: float64
i is :  4 and TrafficRank is :  0     0.005239
1     0.005592
2     0.015223
3     0.006154
4     0.0070

ValueError: Iter value must be between 0 and 10

In [47]:
t10 = TrafficRank(10)
t10

0     0.005011
1     0.005206
2     0.014831
3     0.005906
4     0.006928
        ...   
72    0.002492
73    0.002064
74    0.002274
75    0.047014
76    0.010649
Length: 77, dtype: float64

In [53]:
top5_idx = np.argsort(t10)[::-1][:5]
bot5_idx = np.argsort(t10)[:5]

In [56]:
print("top 5 indices : ", top5_idx.to_list())
print("top 5 values : ", t10[top5_idx])

print("bot 5 indices : ", bot5_idx.to_list())
print("bot 5 values : ", t10[bot5_idx])

top 5 indices :  [7, 31, 27, 5, 75]
top 5 values :  7     0.267301
31    0.189214
27    0.078520
5     0.052742
75    0.047014
dtype: float64
bot 5 indices :  [8, 73, 71, 51, 17]
bot 5 values :  8     0.002045
73    0.002064
71    0.002154
51    0.002175
17    0.002222
dtype: float64


# Question 2

In [2]:
# Q2
!pip install requests

  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Using cached requests-2.32.3-py3-none-any.whl (64 kB)


In [4]:
import requests
stop_url = "https://gist.githubusercontent.com/rg089/35e00abf8941d72d419224cfd5b5925d/raw/12d899b70156fd0041fa9778d657330b024b959c/stopwords.txt"
stopwords_list = requests.get(stop_url).content
stopwords = set(stopwords_list.decode().splitlines())
stopwords = list(stopwords)


def remove_stopwords(low): # low = list of words
    list_ = re.sub(r"[^a-zA-Z0-9]", " ", low.lower()).split()
    return [itm for itm in list_ if itm not in stopwords]

In [5]:
from collections import Counter
import glob
import re

In [ ]:
def top_words(speech_dir):
    speeches = []

    for filepath in glob.glob(f"{speech_dir}/*.txt"):
        with open(filepath, 'r', encoding='utf-8') as f:
            speeches.append(f.read())

    cleaned_speeches = []
    for speech in speeches:
        cleaned_speeches.append(remove_stopwords(speech))
    
    

In [13]:
import numpy as np
def calculate_tf_idf(speech_dir):
    """Calculate TF-IDF for speeches in directory"""
    
    # Read all txt files
    speeches = []
    for filepath in glob.glob(f"{speech_dir}/*.txt"):
        with open(filepath, 'r', encoding='utf-8') as f:
            speeches.append(f.read())

    # Process each speech
    processed_speeches = []
    for speech in speeches:
        filtered_bow = remove_stopwords(speech)
        processed_speeches.append(filtered_bow)
    
    # Calculate document frequencies
    doc_freq = Counter()
    for speech in processed_speeches:
        unique_words = set(speech) # unique for each speech
        for word in unique_words:
            doc_freq[word] += 1
    
    # Calculate IDFs
    N = len(speeches) #total number of documents
    idfs = {}
    for word, df in doc_freq.items(): # df : document frequency
        idfs[word] = np.log((N + 1)/(df + 1)) + 1
    
    tf_idf_scores = []
    # Calculate TF for all speeches combined
    for i, speech in enumerate(processed_speeches):
        # Calculate TF for this document
        doc_length = len(speech)
        word_counts = Counter(speech)
        
        # Calculate TF-IDF for each word in this document
        for word, count in word_counts.items():
            tf = count/doc_length
            tf_idf = tf * idfs[word]
            tf_idf_scores.append((f"{word}_doc{i}", tf_idf))
    
    # Get top 15 words
    top_words = sorted(tf_idf_scores, 
                      key=lambda x: x[1], 
                      reverse=True)[:15]
    
    return top_words

# Example usage
directory = "/Users/yi.hs/cs119/cs-119-bigdata/week3/prez_speeches/kennedy"  # directory with extracted txt files
top_words = calculate_tf_idf(directory)
print("Top 15 most important words:")
for word, score in top_words:
    print(f"{word}: {score:.4f}")

Top 15 most important words:
corps_doc30: 0.1177
catholic_doc41: 0.1051
tax_doc26: 0.0977
religious_doc41: 0.0927
mississippi_doc7: 0.0905
berlin_doc3: 0.0814
peace_doc30: 0.0786
university_doc35: 0.0777
united_doc8: 0.0760
uh_doc44: 0.0633
vanderbilt_doc23: 0.0619
frost_doc0: 0.0618
church_doc41: 0.0618
city_doc3: 0.0605
nuclear_doc4: 0.0586


In [15]:
import os
os.chdir('/Users/yi.hs/cs119/cs-119-bigdata/week3/prez_speeches')

In [18]:
os.getcwd()

'/Users/yi.hs/cs119/cs-119-bigdata/week3/prez_speeches'

In [19]:
import glob
import os

def list_president_files():
    # Assuming we're in the directory containing president folders
    for president_dir in glob.glob("*/"):
        print(f"\nFiles for {president_dir}:")
        for txt_file in glob.glob(f"{president_dir}/*.txt"):
            print(txt_file)

# Example usage
list_president_files()


Files for coolidge/:
coolidge/coolidge_speeches_009.txt
coolidge/coolidge_speeches_008.txt
coolidge/coolidge_speeches_000.txt
coolidge/coolidge_speeches_001.txt
coolidge/coolidge_speeches_003.txt
coolidge/coolidge_speeches_002.txt
coolidge/coolidge_speeches_006.txt
coolidge/coolidge_speeches_007.txt
coolidge/coolidge_speeches_011.txt
coolidge/coolidge_speeches_005.txt
coolidge/coolidge_speeches_004.txt
coolidge/coolidge_speeches_010.txt

Files for tyler/:
tyler/tyler_speeches_017.txt
tyler/tyler_speeches_003.txt
tyler/tyler_speeches_002.txt
tyler/tyler_speeches_016.txt
tyler/tyler_speeches_000.txt
tyler/tyler_speeches_014.txt
tyler/tyler_speeches_015.txt
tyler/tyler_speeches_001.txt
tyler/tyler_speeches_005.txt
tyler/tyler_speeches_011.txt
tyler/tyler_speeches_010.txt
tyler/tyler_speeches_004.txt
tyler/tyler_speeches_012.txt
tyler/tyler_speeches_006.txt
tyler/tyler_speeches_007.txt
tyler/tyler_speeches_013.txt
tyler/tyler_speeches_009.txt
tyler/tyler_speeches_008.txt

Files for wilson

In [21]:
import numpy as np
from collections import Counter
import glob
import re
import requests
import os

def calculate_president_tfidf(target_president):
    # Dictionary to store all speeches for each president
    president_speeches = {}
    
    # Read all speeches for each president
    for president_dir in os.listdir('.'):
        if os.path.isdir(president_dir):
            all_speeches = []
            for filepath in glob.glob(f"{president_dir}/*.txt"):
                with open(filepath, 'r', encoding='utf-8') as f:
                    speech = f.read()
                    filtered_speech = remove_stopwords(speech)
                    all_speeches.extend(filtered_speech)
            president_speeches[president_dir] = all_speeches
    
    # Check if target president exists
    if target_president not in president_speeches:
        raise ValueError(f"President {target_president} not found in directory")
    
    # Calculate document frequencies
    doc_freq = Counter()
    for president, speeches in president_speeches.items():
        unique_words = set(speeches)
        for word in unique_words:
            doc_freq[word] += 1
    
    # Calculate IDFs
    N = len(president_speeches)
    idfs = {}
    for word, df in doc_freq.items():
        idfs[word] = np.log((N + 1)/(df + 1)) + 1
    
    # Calculate TF-IDF for target president
    speeches = president_speeches[target_president]
    total_words = len(speeches)
    word_counts = Counter(speeches)
    
    # Calculate TF-IDF scores
    tfidf_scores = {}
    for word, count in word_counts.items():
        tf = count/total_words
        tfidf_scores[word] = tf * idfs[word]
    
    # Get top 15 words
    top_words = sorted(tfidf_scores.items(), 
                      key=lambda x: x[1], 
                      reverse=True)[:15]
    
    return top_words

In [22]:
top_words = calculate_president_tfidf("kennedy")

In [24]:
print(f"\nTop 15 words for Kennedy:")
for word, score in top_words:
    print(f"{word}: {score:.4f}")


Top 15 words for Kennedy:
uh: 0.0115
kennedy: 0.0093
united: 0.0080
states: 0.0069
people: 0.0062
president: 0.0062
nuclear: 0.0061
nixon: 0.0060
country: 0.0059
senator: 0.0054
today: 0.0053
economic: 0.0051
freedom: 0.0050
soviet: 0.0049
years: 0.0049


In [25]:
top_words_hoover = calculate_president_tfidf("hoover")

print(f"\nTop 15 words for hoover:")
for word, score in top_words_hoover:
    print(f"{word}: {score:.4f}")


Top 15 words for hoover:
government: 0.0120
000: 0.0103
people: 0.0080
economic: 0.0076
federal: 0.0066
american: 0.0064
states: 0.0059
business: 0.0055
country: 0.0052
public: 0.0052
tariff: 0.0050
congress: 0.0049
democratic: 0.0048
great: 0.0047
national: 0.0044
